resolving conversations

diff --git a/.github/workflows/presubmit.yml b/.github/workflows/presubmit.yml
--- a/.github/workflows/presubmit.yml
+++ b/.github/workflows/presubmit.yml
@@ -286,8 +286,6 @@ jobs:
         include:
           - os: macos-latest
             python: 3.8
-            with_cc: OFF
-            with_cpp_tests: ON
     runs-on: [self-hosted, m1]
     steps:
       - uses: actions/checkout@v2
@@ -304,17 +302,16 @@ jobs:
           git fetch origin master
           TAICHI_CMAKE_ARGS=$CI_SETUP_CMAKE_ARGS arch -arm64 python3 build.py build
           cd ..
-          echo `ls dist/*.whl`
+          export NUM_WHL=`ls dist/*.whl | wc -l`
+          if [ $NUM_WHL -ne 1 ]; then echo 'ERROR: created more than 1 whl.' && exit 1; fi
           arch -arm64 python3 -m pip install dist/*.whl
         env:
-          CI_SETUP_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CUDA:BOOL=OFF -DTI_WITH_CC:BOOL=${{ matrix.with_cc }} -DTI_BUILD_TESTS:BOOL=${{ matrix.with_cpp_tests }}
+          CI_SETUP_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CUDA:BOOL=OFF -DTI_WITH_CC:BOOL=OFF -DTI_BUILD_TESTS:BOOL=ON
 
       - name: Test
         run: |
           export PATH=$PATH:$HOME/Library/Python/3.8/bin
           arch -arm64 python3 examples/algorithm/laplace.py
-          arch -arm64 ti diagnose
-          arch -arm64 ti changelog
           TI_LIB_DIR=`arch -arm64 python3 -c "import taichi;print(taichi.__path__[0])" | tail -1`
           [ "$RUN_CPP_TESTS" = "ON" ] && TI_LIB_DIR="$TI_LIB_DIR/lib" arch -arm64 ./build/taichi_cpp_tests
           arch -arm64 ti test -vr2 -t2
