[ci] Change build method of ci tests

diff --git a/.github/workflows/presubmit.yml b/.github/workflows/presubmit.yml
--- a/.github/workflows/presubmit.yml
+++ b/.github/workflows/presubmit.yml
@@ -70,14 +70,18 @@ jobs:
         env:
           CI_PLATFORM: ${{ matrix.os }}
 
-      - name: Build
+      - name: Build & Install
         run: |
           TAICHI_REPO_DIR=`pwd`
           export PATH=$TAICHI_REPO_DIR/taichi-llvm/bin/:$PATH
           export CXX=clang++
-          python misc/ci_setup.py ci
-        env:
-          CI_SETUP_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CC:BOOL=ON -DTI_BUILD_TESTS:BOOL=ON
+          cd python
+          python build.py build
+          pip uninstall taichi -y
+          cd ..
+          NUM_WHL = `ls dist/*.whl | wc -l`
+          if [ $NUM_WHL -ne 1 ]; then echo 'ERROR: created more than 1 whl.' && exit 1; fi
+          pip install dist/*.whl
 
       - name: Test
         run: |
@@ -88,6 +92,7 @@ jobs:
           hash -r
           python examples/algorithm/laplace.py
           ti diagnose
+          ti changelog
           # TODO: make cpp tests work in both release & dev mode.
           # Currently cpp tests only works in dev mode since it depends on the path set there.
           TAICHI_REPO_DIR=$TAICHI_REPO_DIR ./build/taichi_cpp_tests
@@ -127,14 +132,18 @@ jobs:
         env:
           CI_PLATFORM: ${{ matrix.os }}
 
-      - name: Build
+      - name: Build & Install
         run: |
           TAICHI_REPO_DIR=`pwd`
           export PATH=$TAICHI_REPO_DIR/taichi-llvm/bin/:$PATH
           export CXX=clang++
-          python misc/ci_setup.py ci
-        env:
-          CI_SETUP_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CC:BOOL=${{ matrix.with_cc }} -DTI_BUILD_TESTS:BOOL=${{ matrix.with_cpp_tests }}
+          cd python
+          python build.py build
+          pip uninstall taichi -y
+          cd ..
+          NUM_WHL = `ls dist/*.whl | wc -l`
+          if [ $NUM_WHL -ne 1 ]; then echo 'ERROR: created more than 1 whl.' && exit 1; fi
+          pip install dist/*.whl
 
       # [DEBUG] Copy this step around to enable debugging inside Github Action instances.
       #- name: Setup tmate session
@@ -150,6 +159,7 @@ jobs:
           hash -r
           python examples/algorithm/laplace.py
           ti diagnose
+          ti changelog
           # TODO: make cpp tests work in both release & dev mode.
           # Currently cpp tests only works in dev mode since it depends on the path set there.
           [ "$RUN_CPP_TESTS" = "ON" ] && TAICHI_REPO_DIR=$TAICHI_REPO_DIR ./build/taichi_cpp_tests
@@ -171,7 +181,13 @@ jobs:
           export LLVM_DIR=$LLVM_LIB_ROOT_DIR/lib/cmake/llvm
           export CXX=clang++-8
           export PYTHON=/usr/bin/python3
-          $PYTHON misc/ci_setup.py ci
+          cd python
+          python build.py build
+          pip uninstall taichi -y
+          cd ..
+          NUM_WHL = `ls dist/*.whl | wc -l`
+          if [ $NUM_WHL -ne 1 ]; then echo 'ERROR: created more than 1 whl.' && exit 1; fi
+          pip install dist/*.whl
         env:
           LLVM_LIB_ROOT_DIR: /home/taichi/Libs/taichi-llvm-10.0.0
           CI_SETUP_CMAKE_ARGS: -DTI_WITH_PENGL:BOOL=ON -DTI_WITH_CC:BOOL=OFF -DTI_WITH_VULKAN:BOOL=ON
@@ -186,6 +202,7 @@ jobs:
           glewinfo
           $PYTHON examples/algorithm/laplace.py
           ti diagnose
+          ti changelog
           ti test -vr2 -t2
 
   build_and_test_windows:
@@ -219,7 +236,11 @@ jobs:
           clang --version
           cd D:\a\taichi\taichi
           python -m pip install --user numpy pybind11 gitpython
-          python misc/ci_setup.py ci
+          cd python
+          python build.py build
+          python -m pip uninstall taichi -y
+          cd ..
+          python -m pip install dist/*.whl
         env:
           PYTHON: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
           CI_SETUP_CMAKE_ARGS: -G "Visual Studio 16 2019" -A x64 -DLLVM_DIR=C:\taichi_llvm\lib\cmake\llvm
@@ -232,6 +253,7 @@ jobs:
           python -c "import taichi"
           python examples/algorithm/laplace.py
           python bin/taichi diagnose
+          python bin/taichi changelog
           python bin/taichi test -cvr2 -t2
         env:
           PYTHON: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
