[misc] Reorg CI stages

diff --git a/.github/workflows/presubmit.yml b/.github/workflows/presubmit.yml
--- a/.github/workflows/presubmit.yml
+++ b/.github/workflows/presubmit.yml
@@ -34,6 +34,7 @@ jobs:
               echo "::set-output name=run_job::true"
             fi
           done < files.txt
+
   check_code_format:
     name: Check Code Format
     runs-on: ubuntu-latest
@@ -82,52 +83,54 @@ jobs:
           # exit with 1 if there were differences:
           git diff _fake_squash _enforced_format --exit-code
 
-      - name: Pylint
-        run: |
-          if [[ ${{needs.check_files.outputs.run_job}} == false ]]; then
-            exit 0
-          fi
-          # Make sure pylint doesn't regress
-          pylint python/taichi/ --disable=all --enable=$(python scripts/generate_pylint_tags.py)
-          if [ $? -eq 0 ]
-          then
-            echo "PASSED: pylint is happy"
-            exit 0
-          else
-            echo "FAILED: please run the pylint command above and make sure it passes"
-            exit 1
-          fi
+  check_static_analyzer:
+      name: Check Static Analyzer
+      runs-on: ubuntu-latest
+      needs: check_files
+      steps:
+        - uses: actions/checkout@v2
+          with:
+            submodules: "recursive"
 
-  check_clang_tidy:
-    # TODO: Move installation of clang-tidy to docker image
-    name: Check clang-tidy
-    runs-on: ubuntu-latest
-    needs: check_files
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          submodules: "recursive"
-      - name: Get docker images
-        run: |
-          if [[ ${{needs.check_files.outputs.run_job}} == false ]]; then
-            exit 0
-          fi
-          # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
-          echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-          docker pull ghcr.io/taichi-dev/taichidev-cpu-ubuntu18.04:v0.1.0
-        env:
-          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
-      - name: Run clang-tidy
-        run: |
-          if [[ ${{needs.check_files.outputs.run_job}} == false ]]; then
-            exit 0
-          fi
-          docker run -id --user dev --name check_clang_tidy ghcr.io/taichi-dev/taichidev-cpu-ubuntu18.04:v0.1.0 /bin/bash
-          tar -cf - ../${{ github.event.repository.name }} --mode u=+rwx,g=+rwx,o=+rwx --owner dev --group dev | docker cp - check_clang_tidy:/home/dev/
-          docker exec --user root check_clang_tidy apt install -y clang-tidy-10
-          docker exec --user dev check_clang_tidy /home/dev/taichi/.github/workflows/scripts/check_clang_tidy.sh "$CI_SETUP_CMAKE_ARGS"
-        env:
-          CI_SETUP_CMAKE_ARGS: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CC:BOOL=ON -DTI_WITH_VULKAN:BOOL=OFF -DTI_BUILD_TESTS:BOOL=OFF
+        - name: Set up Python ${{ matrix.python-version }}
+          uses: actions/setup-python@v2
+          with:
+            python-version: 3.8
+
+        - name: Pylint
+          run: |
+            if [[ ${{needs.check_files.outputs.run_job}} == false ]]; then
+              exit 0
+            fi
+            # Make sure pylint doesn't regress
+            pylint python/taichi/ --disable=all --enable=$(python scripts/generate_pylint_tags.py)
+            if [ $? -eq 0 ]
+            then
+              echo "PASSED: pylint is happy"
+              exit 0
+            else
+              echo "FAILED: please run the pylint command above and make sure it passes"
+              exit 1
+            fi
+
+        - name: clang-tidy
+          run: |
+            if [[ ${{needs.check_files.outputs.run_job}} == false ]]; then
+              exit 0
+            fi
+            # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
+            echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+            docker pull ghcr.io/taichi-dev/taichidev-cpu-ubuntu18.04:v0.1.0
+            if [[ ${{needs.check_files.outputs.run_job}} == false ]]; then
+              exit 0
+            fi
+            docker run -id --user dev --name check_clang_tidy ghcr.io/taichi-dev/taichidev-cpu-ubuntu18.04:v0.1.0 /bin/bash
+            tar -cf - ../${{ github.event.repository.name }} --mode u=+rwx,g=+rwx,o=+rwx --owner dev --group dev | docker cp - check_clang_tidy:/home/dev/
+            docker exec --user root check_clang_tidy apt install -y clang-tidy-10
+            docker exec --user dev check_clang_tidy /home/dev/taichi/.github/workflows/scripts/check_clang_tidy.sh "$CI_SETUP_CMAKE_ARGS"
+          env:
+            CR_PAT: ${{ secrets.GITHUB_TOKEN }}
+            CI_SETUP_CMAKE_ARGS: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CC:BOOL=ON -DTI_WITH_VULKAN:BOOL=OFF -DTI_BUILD_TESTS:BOOL=OFF
 
   build_and_test_cpu_required:
     # This job will be required to pass before merging to master branch.
