[ci] Add Apple M1 buildbot (#2731)
* squashed

* resolving conversations

* retry

* no async

* add async

* extension

* test rm

* test rm

* add arm64 extension

* add metal extension

* remove async

* remove quant

* add comment

* vr2

* ext

* revert

* close unified memory on osx

* add async

* Auto Format

* ban mpm88_async

* vr2

* Disable Async

* presubmit

Co-authored-by: Taichi Gardener <taichigardener@gmail.com>

diff --git a/.github/workflows/presubmit.yml b/.github/workflows/presubmit.yml
--- a/.github/workflows/presubmit.yml
+++ b/.github/workflows/presubmit.yml
@@ -277,3 +277,42 @@ jobs:
           python bin/taichi test -vr2 -t2
         env:
           PYTHON: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
+
+  build_and_test_m1:
+    name: Build and Test (Apple M1)
+    needs: check_code_format
+    strategy:
+      matrix:
+        include:
+          - os: macos-latest
+            python: 3.8
+    runs-on: [self-hosted, m1]
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
+
+      - name: Build
+        run: |
+          arch -arm64 python3 -m pip uninstall taichi -y
+          rm -rf $HOME/Library/Python/3.8/lib/python/site-packages/taichi
+          git --version
+          export CXX=clang++
+          arch -arm64 python3 -m pip install -r requirements_dev.txt
+          cd python
+          git fetch origin master
+          TAICHI_CMAKE_ARGS=$CI_SETUP_CMAKE_ARGS arch -arm64 python3 build.py build
+          cd ..
+          export NUM_WHL=`ls dist/*.whl | wc -l`
+          if [ $NUM_WHL -ne 1 ]; then echo 'ERROR: created more than 1 whl.' && exit 1; fi
+          arch -arm64 python3 -m pip install dist/*.whl
+        env:
+          CI_SETUP_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CUDA:BOOL=OFF -DTI_WITH_CC:BOOL=OFF -DTI_BUILD_TESTS:BOOL=ON
+
+      - name: Test
+        run: |
+          export PATH=$PATH:$HOME/Library/Python/3.8/bin
+          arch -arm64 python3 examples/algorithm/laplace.py
+          TI_LIB_DIR=`arch -arm64 python3 -c "import taichi;print(taichi.__path__[0])" | tail -1`
+          TI_LIB_DIR="$TI_LIB_DIR/lib" arch -arm64 ./build/taichi_cpp_tests
+          arch -arm64 ti test -t2 -x
