remove-old-macos-ci

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -112,76 +112,76 @@ jobs:
           CR_PAT: ${{ secrets.GITHUB_TOKEN }}
           CI_SETUP_CMAKE_ARGS: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTI_WITH_OPENGL:BOOL=ON -DTI_WITH_VULKAN:BOOL=ON -DTI_BUILD_TESTS:BOOL=ON -DTI_WITH_BACKTRACE:BOOL=ON
 
-  build_and_test_cpu_mac:
-    name: Build and Test macos (CPU)
-    needs: check_files
-    timeout-minutes: ${{ github.event.schedule != '0 18 * * *' && 120 || 180 }}
-    strategy:
-      matrix:
-        include:
-          - os: macos-10.15
-            python: 3.11
-            with_cpp_tests: ON
-            wanted_archs: 'cpu,vulkan'
-    runs-on:
-    - self-hosted
-    - ${{ matrix.os }}
-    env:
-      PY: ${{ matrix.python }}
-      TAICHI_CMAKE_ARGS: >-
-        -DTI_WITH_OPENGL:BOOL=OFF
-        -DTI_WITH_VULKAN:BOOL=ON
-        -DTI_WITH_C_API=ON
-        -DTI_BUILD_TESTS:BOOL=${{ matrix.with_cpp_tests }}
-    steps:
-      - name: Workaround checkout issues
-        run: |
-          . .github/workflows/scripts/common-utils.sh
-          git submodule foreach 'git rev-parse HEAD > /dev/null 2>&1 || rm -rf $PWD' || true
-          unset-git-caching-proxy
+  #build_and_test_cpu_mac:
+  #  name: Build and Test macos (CPU)
+  #  needs: check_files
+  #  timeout-minutes: ${{ github.event.schedule != '0 18 * * *' && 120 || 180 }}
+  #  strategy:
+  #    matrix:
+  #      include:
+  #        - os: macos-10.15
+  #          python: 3.11
+  #          with_cpp_tests: ON
+  #          wanted_archs: 'cpu,vulkan'
+  #  runs-on:
+  #  - self-hosted
+  #  - ${{ matrix.os }}
+  #  env:
+  #    PY: ${{ matrix.python }}
+  #    TAICHI_CMAKE_ARGS: >-
+  #      -DTI_WITH_OPENGL:BOOL=OFF
+  #      -DTI_WITH_VULKAN:BOOL=ON
+  #      -DTI_WITH_C_API=ON
+  #      -DTI_BUILD_TESTS:BOOL=${{ matrix.with_cpp_tests }}
+  #  steps:
+  #    - name: Workaround checkout issues
+  #      run: |
+  #        . .github/workflows/scripts/common-utils.sh
+  #        git submodule foreach 'git rev-parse HEAD > /dev/null 2>&1 || rm -rf $PWD' || true
+  #        unset-git-caching-proxy
 
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: '0'
-          submodules: 'recursive'
+  #    - uses: actions/checkout@v3
+  #      with:
+  #        fetch-depth: '0'
+  #        submodules: 'recursive'
 
-      - name: Prepare Environment
-        run: |
-          . .github/workflows/scripts/common-utils.sh
-          prepare-build-cache
-        env:
-          PLATFORM: 'macos'
+  #    - name: Prepare Environment
+  #      run: |
+  #        . .github/workflows/scripts/common-utils.sh
+  #        prepare-build-cache
+  #      env:
+  #        PLATFORM: 'macos'
 
-      - name: Build & Install
-        if: needs.check_files.outputs.run_job == 'true'
-        run: |
-          # Use the molten-vk v1.1.10 downloaded from taichi assets
-          brew uninstall molten-vk -f
-          .github/workflows/scripts/build.py
-        env:
-          CXX: clang++
+  #    - name: Build & Install
+  #      if: needs.check_files.outputs.run_job == 'true'
+  #      run: |
+  #        # Use the molten-vk v1.1.10 downloaded from taichi assets
+  #        brew uninstall molten-vk -f
+  #        .github/workflows/scripts/build.py
+  #      env:
+  #        CXX: clang++
 
-      # [DEBUG] Copy this step around to enable debugging inside Github Action instances.
-      #- name: Setup tmate session
-      #  uses: mxschmitt/action-tmate@v3
-      #  with:
-      #    limit-access-to-actor: true
+  #    # [DEBUG] Copy this step around to enable debugging inside Github Action instances.
+  #    #- name: Setup tmate session
+  #    #  uses: mxschmitt/action-tmate@v3
+  #    #  with:
+  #    #    limit-access-to-actor: true
 
-      - name: Test
-        id: test
-        if: needs.check_files.outputs.run_job == 'true'
-        run: .github/workflows/scripts/unix_test.sh
-        env:
-          TI_WANTED_ARCHS: ${{ matrix.wanted_archs }}
-          TI_SKIP_CPP_TESTS: Disabled because Vulkan is supported but not working on buildbot4
+  #    - name: Test
+  #      id: test
+  #      if: needs.check_files.outputs.run_job == 'true'
+  #      run: .github/workflows/scripts/unix_test.sh
+  #      env:
+  #        TI_WANTED_ARCHS: ${{ matrix.wanted_archs }}
+  #        TI_SKIP_CPP_TESTS: Disabled because Vulkan is supported but not working on buildbot4
 
-      - name: Save wheel if test failed
-        if: failure() && steps.test.conclusion == 'failure'
-        uses: actions/upload-artifact@v3
-        with:
-          name: broken-wheel
-          path: dist/*
-          retention-days: 7
+  #    - name: Save wheel if test failed
+  #      if: failure() && steps.test.conclusion == 'failure'
+  #      uses: actions/upload-artifact@v3
+  #      with:
+  #        name: broken-wheel
+  #        path: dist/*
+  #        retention-days: 7
 
   build_and_test_gpu_linux:
     name: Build and Test (GPU)
